remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
gem "github-pages", group: :jekyll_plugins
title: [The title of your site]
description: [A short description of your site's purpose]
